apiVersion: v1
kind: Pod
metadata:
  name: goodpod01
  labels:
    app: myapp
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    readinessProbe:
      tcpSocket:
        port: 8080
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 7070
      periodSeconds: 20
