apiVersion: v1
kind: Pod
metadata:
  name: addcap-goodpod09
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
  - name: initcontainer02
    image: busybox:1.35
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
  containers:
  - name: container01
    image: busybox:1.35

