---
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: container01
    image: busybox:1.35
  securityContext:
    seLinuxOptions:
      type: spc_t
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod03
spec:
  containers:
  - name: container01
    image: busybox:1.35
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod04
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: container_kvm_t
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod05
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod06
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
  - name: initcontainer02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod07
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: container_kvm_t
  - name: initcontainer02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: spc_t
  containers:
  - name: container01
    image: busybox:1.35
