###### Deployments - Bad
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      securityContext:
        seLinuxOptions:
          user: sysadm_u
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      securityContext:
        seLinuxOptions:
          role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      securityContext:
        seLinuxOptions:
          user: sysadm_u
          role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
            role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      - name: container02
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      - name: container02
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
      - name: container02
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
            role: sysadm_r
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            type: unconfined_t
      - name: container02
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            role: sysadm_r
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
            role: sysadm_r
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer02
        image: busybox:1.35
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer02
        image: busybox:1.35
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            role: sysadm_r
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer02
        image: busybox:1.35
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
            role: sysadm_r
      containers:
      - name: container01
        image: busybox:1.35
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selur-baddeployment17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer02
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            type: container_init_t
      - name: initcontainer01
        image: busybox:1.35
        securityContext:
          seLinuxOptions:
            user: sysadm_u
      containers:
      - name: container01
        image: busybox:1.35
