---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod01
spec:
  containers:
  - name: container01
    image: busybox:1.35
  securityContext:
    seLinuxOptions:
      user: sysadm_u
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod02
spec:
  containers:
  - name: container01
    image: busybox:1.35
  securityContext:
    seLinuxOptions:
      role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod03
spec:
  containers:
  - name: container01
    image: busybox:1.35
  securityContext:
    seLinuxOptions:
      user: sysadm_u
      role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod04
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod05
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod06
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
        role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod07
spec:
  containers:
  - name: container01
    image: busybox:1.35
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod08
spec:
  containers:
  - name: container01
    image: busybox:1.35
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod09
spec:
  containers:
  - name: container01
    image: busybox:1.35
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
        role: sysadm_r
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod10
spec:
  containers:
  - name: container01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: unconfined_t
  - name: container02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod11
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod12
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        role: sysadm_r
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod13
spec:
  initContainers:
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
        role: sysadm_r
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod14
spec:
  initContainers:
  - name: initcontainer02
    image: busybox:1.35
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod15
spec:
  initContainers:
  - name: initcontainer02
    image: busybox:1.35
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        role: sysadm_r
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod16
spec:
  initContainers:
  - name: initcontainer02
    image: busybox:1.35
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
        role: sysadm_r
  containers:
  - name: container01
    image: busybox:1.35
---
apiVersion: v1
kind: Pod
metadata:
  name: selur-badpod17
spec:
  initContainers:
  - name: initcontainer02
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        type: container_init_t
  - name: initcontainer01
    image: busybox:1.35
    securityContext:
      seLinuxOptions:
        user: sysadm_u
  containers:
  - name: container01
    image: busybox:1.35
