apiVersion: v1
kind: Pod
metadata:
  name: goodpod02
spec:
  containers:
  - name: ghost
    image: ghost
    securityContext:
      readOnlyRootFilesystem: true
  - name: nginx
    image: nginx
    securityContext:
      readOnlyRootFilesystem: true
