name: Kuttl tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.N4K_NEW_LICENSE }}
jobs:
  run-e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        run: make kind-create-cluster
      - name: testing secret
        run: |
          echo "$DEVOPS"
        env:
          DEVOPS: ${{ secrets.N4K_LICENSE }}
      - name: Install kyverno
        run: make kind-deploy-kyverno       
      - name: Wait for Kyverno to start
        run: make wait-for-kyverno
      - name: Test with kuttl
        run: make test-kuttl
