name: Kuttl tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        run: make kind-create-cluster
      # - name: testing secret
      #   run: |
      #     echo "$DEVOPS"
      #    # echo "$DEVOPS" | sed 's/./& /g' 
      #   env:
      #     DEVOPS: ${{ secrets.N4K_LICENSE }}
      - name: Install kyverno
        run: |
          export N4K_LICENSE_KEY="$LICENSE_KEY"
          make kind-deploy-kyverno
        env:
          LICENSE_KEY: ${{ secrets.N4K_LICENSE }}      
      - name: Wait for kyverno ready
        run: make wait-for-kyverno        
      - name: Test with kuttl
        run: make test-kuttl
