name: Kuttl tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.N4K_NEW_LICENSE }}
jobs:
  run-e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        run: make kind-create-cluster
      - name: Install kyverno
        run: make kind-deploy-kyverno       
      - name: Wait for Kyverno to start
        run: sleep 60
      - name: Wait for Kyverno to start
        shell: bash
        run: |
          kubectl wait --namespace kyverno --for=condition=ready pod --all --timeout=60s
      - name: Test with kuttl
        run: make test-kuttl
