name: Kuttl tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  run-e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        run: make kind-create-cluster
      - name: Install kyverno
        with: # Set the secret as an input
          super_secret: ${{ secrets.N4K_LICENSE }}
        run: make kind-deploy-kyverno
      - name: Wait for Kyverno to start
        run: sleep 60
      - name: check kyverno
        run: kubectl get po -A
      - name: Test with kuttl
        run: make test-kuttl
