name: Kuttl tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  run-e2etest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        run: make kind-create-cluster
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.N4K_LICENSE }}
          echo "Trick to echo GitHub Actions Secret:  "
      - name: Install kyverno
        run: make kind-deploy-kyverno
      - name: Wait for Kyverno to start
        run: sleep 60
      - name: check kyverno
        run: kubectl get po -A
      - name: Test with kuttl
        run: make test-kuttl
